// board
const BOARD_RADIUS_SCALE = 0.12;
const BOARD_X_OFFSET = 0.5;
const BOARD_Y_OFFSET = 0.16;
const BOARD_RINGS = 10;
const BOARD_TEXT_PADDING = 0.1;
const BOARD_AMPLITUDE_X = 50;
const BOARD_AMPLITUDE_Y = 10;
const BOARD_PERIOD_X = 7500;
const BOARD_PERIOD_Y = 5000;

// throwing
const DISTANCE_AMPLIFIER_X = 0.5;
const DISTANCE_AMPLIFIER_Y = 0.65;
const SWIPE_DURATION_BASE_MS = 1000;
const MIN_DISTANCE = 0.15;

// arrow
const ARROW_WIDTH = 111;
const ARROW_HEIGHT = 520;
const ARROW_CENTERPOINT_X = 62;
const ARROW_CENTERPOINT_Y = 108;
const ARROW_SCALE = 0.5; // calc = canvas height / arrow-height / scale
const ARROW_X_OFFSET = 0.5;
const ARROW_Y_OFFSET = 0.75;

const HIT_SPEED = 0.06;

// Background
const BG_LANDSCAPE_WIDTH = 2100;
const BG_LANDSCAPE_HEIGHT = 1170;
const BG_LANDSCAPE_ACHOR_X = 1050;
const BG_LANDSCAPE_ACHOR_y = 585;

const BG_PORTRAIT_WIDTH = 1170;
const BG_PORTRAIT_HEIGHT = 2110;
const BG_PORTRAIT_ACHOR_X = 585;
const BG_PORTRAIT_ACHOR_y = 1055;

const ENCRYPTION_ENABLE = true;

// DEFAULTS
const BOARD_DEFAULT = {
  radius: 0,
  x: 0,
  y: 0,
  amplitudeY: BOARD_AMPLITUDE_Y,
  amplitudeX: BOARD_AMPLITUDE_X,
  periodX: BOARD_PERIOD_X,
  periodY: BOARD_PERIOD_Y,
};

const ARROW_DEFAULT = {
  x: 0,
  y: 0,
  scale: 1,
  imageState: 0,
  amplitude: 10, // used for bounch
  period: 1000, // used for bounch
};

export {
  BOARD_RADIUS_SCALE,
  BOARD_X_OFFSET,
  BOARD_Y_OFFSET,
  BOARD_AMPLITUDE_X,
  BOARD_AMPLITUDE_Y,
  BOARD_PERIOD_X,
  BOARD_PERIOD_Y,
  DISTANCE_AMPLIFIER_X,
  DISTANCE_AMPLIFIER_Y,
  SWIPE_DURATION_BASE_MS,
  MIN_DISTANCE,
  BOARD_DEFAULT,
  ARROW_DEFAULT,
  ARROW_WIDTH,
  ARROW_HEIGHT,
  ARROW_CENTERPOINT_X,
  ARROW_CENTERPOINT_Y,
  ARROW_SCALE,
  ARROW_X_OFFSET,
  ARROW_Y_OFFSET,
  HIT_SPEED,
  BOARD_RINGS,
  BOARD_TEXT_PADDING,
  BG_LANDSCAPE_WIDTH,
  BG_LANDSCAPE_HEIGHT,
  BG_LANDSCAPE_ACHOR_X,
  BG_LANDSCAPE_ACHOR_y,
  BG_PORTRAIT_WIDTH,
  BG_PORTRAIT_HEIGHT,
  BG_PORTRAIT_ACHOR_X,
  BG_PORTRAIT_ACHOR_y,
  ENCRYPTION_ENABLE,
};
